In [0]:
import numpy as np

In [0]:
samples = np.array([[0,0],[0,1],[1,0],[1,1]])
epochs = 5
initial_weights = np.array([0.3,-0.1])
threshold = 0.2
rate = 0.1

In [0]:
out = [(var[0] & ~var[1]) | (~var[0] & var[1]) for var in samples] # XOR
out = [var[0] & var[1] for var in samples] # AND
out = [var[0] | var[1] for var in samples] # OR

In [6]:
def Activation_fn(weighted_sum,threshold):
  if(weighted_sum < threshold):
    return 0
  else:
    return 1
def loss(samples, weights, outputs, threshold):
  # error = np.zeros(len(samples))
  # for i in range(len(samples)):
  #   error[i] = outputs[i] - Activation_fn(round(weights.dot(samples[i]),1), threshold)
  error = outputs - np.array([Activation_fn(round(weights.dot(var),1),threshold) for var in samples])
  return error
loss(samples,initial_weights,out,threshold)

array([0, 1, 0, 0])

In [7]:
print("initial_weights : ",initial_weights)
weights = initial_weights
errorEpoch  = loss(samples, weights, out, threshold)
prevErr = np.zeros(len(samples))
totalEpochs = 0
change = 0
while not (errorEpoch == np.zeros(len(samples))).all():
  totalEpochs += 1
  if (prevErr == errorEpoch).all() :
    change+=1
  else:
    change = 0
  if change >= epochs:
    break
  prevErr = errorEpoch
  for i in range(samples.shape[0]):
    dot_prod = round(weights.dot(samples[i]),1)
    weights = weights + rate * (out[i] - Activation_fn(dot_prod, threshold)) * samples[i]
  errorEpoch  = loss(samples, weights, out, threshold)
  print(errorEpoch)
print(weights, totalEpochs)
    # print(weights , samples[i] ,  rate * (out[i] - Activation_fn(dot_prod, threshold)) * samples[i] , dot_prod)
# print(weights , error)   

initial_weights :  [ 0.3 -0.1]
[0 1 0 0]
[0 1 0 0]
[0 0 0 0]
[0.3 0.2] 3
